### ISSUE TITLE
Packages/app.rive.rive-unity/Runtime/Libraries/Android has no meta file, but it's in an immutable folder. The asset will be ignored.

### ISSUE THREAD

**Issue by tomkail** [rive-app/rive-unity#19]
Reproducible on our iOS project by importing the package. Doesn't appear to prevent the package working, but it spams the console with errors constantly.
Throws for several files in the Android folder.
<img width="567" alt="image" src="https://github.com/rive-app/rive-unity/assets/1252816/2f2e29c4-2265-49a2-aaba-d13c4cd0352b">

**Comment by luigi-rosso** [comment]
This has been added in [v0.1.79](https://github.com/rive-app/rive-unity/releases/tag/v0.1.79) could you try it and confirm you are no longer getting the issue?

**Comment by Adeptus-Astartes** [comment]
v 0.1.87 doesn't have that issue, but at runtime it throws DllNotFoundException: Unable to load DLL 'rive'. Tried the load the following dynamic libraries: Unable to load dynamic library 'rive' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "rive" not found
03-04 16:10:40.038 26220 26285 E Unity   :   at Rive.RenderQueue.unrefRenderQueue (System.IntPtr renderQueue) [0x00000] in <00000000000000000000000000000000>:0 
03-04 16:10:40.038 26220 26285 E Unity   :   at Rive.RenderQueue.Finalize () [0x00000] in <00000000000000000000000000000000>:0

**Comment by damzobridge** [comment]
This should be fixed from [v0.1.174](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188) upwards. Please upgrade and let us know if you're still running into issues.
