### ISSUE TITLE
Rive Unity Sripting Backend issue for Android

### ISSUE THREAD

**Issue by Adam418** [rive-app/rive-unity#22]
I am testing Rive animations on Android and iOS devices using Unity3d.

When I change Scripting Backend to IL2CPP all the animations of Rive stuff vanishes. 

Couldn't find any workaround or help regarding this.

Tested on Samsung  S23 Ultra and Galaxy S7 (released March 2016). In some cases it showed the animation on Galaxy S7 rather than the later and more powerful S23.

Dev machine: Mac Studio M2 chip
Unity version: 2022.3.16f1
Rive.app package version 0.1.70

![rive android](https://github.com/rive-app/rive-unity/assets/7951545/eaf718ba-b7c3-4acf-9503-a994c4fe6f1c)

**Comment by Adeptus-Astartes** [comment]
Same issue here

**Comment by Adeptus-Astartes** [comment]
S21, IL2CPP - > DllNotFoundException: Unable to load DLL 'rive'. Tried the load the following dynamic libraries: Unable to load dynamic library 'rive' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "rive" not found
03-04 16:10:39.975 26220 26266 E Unity   :   at Rive.NativeLibrary.setUnityLog (Rive.NativeLibrary+LogDelegate callback) [0x00000] in <00000000000000000000000000000000>:0 

Plugin Version rive-unity-0.1.87

**Comment by jleblancsw** [comment]
What settings are you using to get this to work on Android?

I'm using Built-in Rendering Pipeline
I've tried GLES2, GLES3
I've tried Scripting Backend Mono, IL2CPP
I've tried ARMv7, ARM64

Every time I get a black texture and an error "Failed to load TextAsset "blahblah" as a Rive File.
NullReferenceException: Object reference not set to an instance of an object.
RiveTexture.Start()(at<0d59........................)

**Comment by jleblancsw** [comment]
I needed to force Unity to build for OpenGL instead of Vulkan:
Turn of "Auto Graphics API" in Unity's Project Settings->Player->Other Settings and remove Vulkan and use ES3

It also appears that the arm64 shared library for Rive is actually 32bit so I had to build for armv7

**Comment by damzobridge** [comment]
This should be fixed from [v0.1.188](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188). Please upgrade and let us know if you're still running into issues.

As mentioned above, you'll want to make sure you remove Vulkan from the list of Graphics APIs.
