### ISSUE TITLE
ARM64 not supported

### ISSUE THREAD

**Issue by BitBarrel** [rive-app/rive-unity#45]
I noticed that for running on Android, the target architecture has to be set to ARMv7 only, (not both ARM64 and ARMv7 or only ARM64), otherwise Rive won't render. This is not documented anywhere.

**Comment by damzobridge** [comment]
Thanks for reporting this. It's not in the docs because we currently build the plugin to support both architectures, so it _should_ work.

When you ran this on the different devices, did you happen to have any logs that might help us debug this further?  We're working on reproducing this on our end as well.

**Comment by BitBarrel** [comment]
I don't have any logs but my phone is a Galaxy S22 Ultra.

**Comment by jleblancsw** [comment]
I saw there was a shared library for arm64 in your Rive plugin package.
I'm trying to use it but I'm getting this error in logcat:
2024/06/21 12:41:38.091 21597 21617 Debug Unity Failed to load native plugin: Unable to load library '/data/app/~~YwtVlBSerVMcl9vcfHEXeQ==/com.name.name_BiRP-BnLiRS2QcRoiO67PAVJFKQ==/lib/arm64/librive.so', error 'java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~YwtVlBSerVMcl9vcfHEXeQ==/com.name.name_BiRP-BnLiRS2QcRoiO67PAVJFKQ==/lib/arm64/librive.so" is 32-bit instead of 64-bit'

It seems to think that library is 32-bit. Is that shared library really built for 64-bit?
![image](https://github.com/rive-app/rive-unity/assets/173206286/2f3be1b9-c659-47cd-871f-bbba2e6fbda3)
In the inspector it seems to be telling Unity to use it as 64-bit so that seems right. It seems like the shared library itself is 32bit?

**Comment by jleblancsw** [comment]
/librive.so:     file format elf32-little
architecture: UNKNOWN!, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00000000

Ah yeah that shared library in the arm64 folder is actually 32-bit

**Comment by damzobridge** [comment]
Thanks @jleblancsw ! Your logs were really helpful. We have a fix coming for this soon!

**Comment by damzobridge** [comment]
Hi @jleblancsw , this should be available from [v0.1.188](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188) !
