### ISSUE TITLE
WebGL error spam

### ISSUE THREAD

**Issue by BlenMiner** [rive-app/rive-unity#46]
![image](https://github.com/rive-app/rive-unity/assets/4602596/60b254bb-b596-4046-a573-c9c5bbcecee1)

StateMachine exceeded max iterations.

This seems to be called when the statemachine reached its end and I keep calling the Advance function.
This didn't happen before and doesn't happen in the editor.

**Comment by HayesGordon** [comment]
Hi @BlenMiner, This is a problem with your state machine setup. If you open this file in the Rive Editor, you'll also note the same output in the Rive console. This indicates that your state machine is constantly iterating and not settling.

I'll close this issue here as it's unrelated to the `rive-unity` runtime. But if you need additional support, please reach out to our support forum: https://rive.app/community/forums/home

You can share the `.rev` file there, and someone can take a look.

If it's a sensitive file, you can share it through [this support link](https://rive.app/community/forums/home).
