### ISSUE TITLE
Latest package causes compile errors

### ISSUE THREAD

**Issue by BitBarrel** [rive-app/rive-unity#83]
This package causes errors:
https://github.com/rive-app/rive-unity.git?path=package#v0.3.1-canary.36

![Rive errors](https://github.com/user-attachments/assets/22d7fde0-418d-4594-a570-4aa03ac9998b)

**Comment by damzobridge** [comment]
Which version of Unity are you using?

**Comment by damzobridge** [comment]
Also, I'm curious, did you remove the default Unity UI package (`com.unity.ugui`) from your project at some point? Those types are from that package.

**Comment by BitBarrel** [comment]
I am using Unity 6000.0.23f1

I did remove the Unity UI package at one point because it wasn't required but I guess now it is required. Adding that package fixed the error. Please add to the documentation that this package is a required dependency.

**Comment by damzobridge** [comment]
Oh, thanks—that’s really helpful to know. Those errors shouldn’t have been logged, so it’s something we plan to address before the official v0.3.1 release.

The canary versions are great for trying out new features and updates, but are more likely to have bugs. The non-canary releases go through more thorough QA and typically come with supporting documentation.

The upcoming v0.3.1 release will include the new RivePanel and RiveWidget components, which depend on `com.unity.ugui` because they use the EventSystem for pointer input. We’re considering either including `com.unity.ugui` as a package dependency or making it optional, with the caveat that the new components and scripts won’t show up unless the package is installed.
